level: trace  # 全局日志级别 trace, debug, info, warn, error, fatal, panic

webui:
  access_key: "123456"
  port: 9529
  ip: "0.0.0.0"

gateway:
  ip: "0.0.0.0"    # server ip
  port: 9528       # server port
  debug_info: true # 是否开启调试

clients:
  - client_id: "test"
    listeners:
      - client_id: "test"
        encrypt: true
        debug_info: false
        public_protocol: "udp"
        public_ip: "0.0.0.0"
        public_port: 9092
        internal_ip: "114.114.114.114"
        internal_port: 53
      
      - client_id: "test"
        encrypt: true
        public_protocol: "tcp"
        public_ip: "0.0.0.0"
        public_port: 9093
        internal_ip: "127.0.0.1"
        internal_port: 8000 