level= "warn" # 全局日志级别 trace, debug, info, warn, error, fatal , panic 

[gateway]
ip = "0.0.0.0"    # server ip
port = 9528       # server port
debug_info = false # 是否开启调试

[[listeners]]
client_id = "test"
encrypt = true                  # 是否开启加密
debug_info = false               # 是否开启调试
public_protocol = "udp"         # 协议
public_ip = "0.0.0.0"
public_port = 9092
internal_ip = "114.114.114.114"
internal_port = 53

[[listeners]]
client_id = "test"
encrypt = true            # 是否开启加密 
public_protocol = "tcp"   # 协议
public_ip = "0.0.0.0"
public_port = 9093
internal_ip = "127.0.0.1"
internal_port = 8000
