[gateway]
ip = "0.0.0.0" # server ip
port = 9527 # server port

[[listeners]]
client_id = "test" 
public_protocol = "udp" # 协议
public_ip = "0.0.0.0" 
public_port = 9091
internal_protocol = "udp"
internal_ip = "114.114.114.114"
internal_port = 53
