[gateway]
ip = "0.0.0.0"
port = 9527

[[listeners]]
client_id = "test"
public_protocol = "tcp"
public_ip = "0.0.0.0"
public_port = 9091
internal_protocol = "tcp"
internal_ip = "127.0.0.1"
internal_port = 8000
